"""create table

Revision ID: 132d6c3dc3c1
Revises: 
Create Date: 2020-09-11 13:24:40.268052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132d6c3dc3c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
